Inline Documentation for Order.js and OrderDataTable.js
codebase-berkeley/ethical-internal-website pull request #36
Opened 2019-11-07 04:05 UTC by micahelinor

- [ ] Inline documentation for functions and some variables in those two files.

2019-11-10 05:09 UTC, abaruah117 requested changes
use /* */ for multiline.

2019-11-10 19:37 UTC, trev4ev submitted a review, later dismissed
lgtm

2019-11-14 02:55 UTC, trev4ev requested changes
small changes!

2019-11-14 02:55 UTC, trev4ev commented on src/components/OrderDataTable.js
> +                  /*Arrow function that returns true if Date values are
Make your comment look like this

```
/*
line 1 blah blah
blah blah
*/

2019-11-14 02:55 UTC, trev4ev commented on src/components/Orders.js
> +    //this variable arrayOfObjects converts a nested array to an array of objects
this should also be multiline

2019-11-17 18:52 UTC, trev4ev commented
@micahelinor @jamesli898 please make these changes so this can get merged in

2019-11-17 19:17 UTC, abaruah117 submitted a review, later dismissed
lgtm but please make trevor's changes(multiline formatting)

2019-11-18 23:46 UTC, trev4ev requested changes
please be sure to fix all changes before requesting a review

2019-11-18 23:46 UTC, trev4ev commented on src/components/OrderDataTable.js
> +                  /*Arrow function that returns true if Date values are
this change was not fixed

2019-11-20 18:40 UTC, abaruah117 requested changes
please make sure to address ALL comments before requesting a review.

2019-11-20 18:40 UTC, abaruah117 commented on src/components/OrderDataTable.js
> +                      /*Date.parse method parses a string representation of a date,
this also isn't a proper multiline comment, see trevor's comments.

2019-11-20 18:40 UTC, abaruah117 commented on src/components/Orders.js
> +    since react table needed an array of objects as input.*/
also not fixed.

2019-11-24 19:05 UTC, abaruah117 requested changes
please make sure to read all comments and address all requested changes before requesting a review.

2019-11-24 19:05 UTC, abaruah117 commented on src/components/OrderDataTable.js
> +                  /*Arrow function that returns true if Date values are
again, this is the 3rd iteration that you haven't changed these to proper format, see trevor's comments.

2019-11-24 19:05 UTC, abaruah117 commented on src/components/OrderDataTable.js
> +                      /*Date.parse method parses a string representation of a date,
again

2019-11-24 19:05 UTC, abaruah117 commented on src/components/Orders.js
> +    since react table needed an array of objects as input.*/
fix this

2019-11-24 21:45 UTC, micahelinor commented on src/components/OrderDataTable.js
> +                  /*Arrow function that returns true if Date values are
got it

2019-11-24 21:46 UTC, micahelinor commented on src/components/Orders.js
> +    //this variable arrayOfObjects converts a nested array to an array of objects
got it

2019-11-24 21:46 UTC, micahelinor commented on src/components/Orders.js
> +    since react table needed an array of objects as input.*/
goit it

2019-11-24 21:54 UTC, abaruah117 submitted a review, later dismissed
lgtm

2019-11-24 22:26 UTC, micahelinor commented
@trev4ev need to approve

2019-11-25 00:30 UTC, micahelinor commented
@trev4ev

2019-11-25 05:16 UTC, merged