Implemented the inventory table as a react table and added styling to DataTable.css
codebase-berkeley/ethical-internal-website pull request #41
Opened 2019-11-17 04:09 UTC by katelyn-schmidt

(solves issues #19 and #40 )
1. Updated inventory.js and DataTable.js to use react table by referencing the existing react table for the orders table. 
2. Added styling to DataTable.css including:
- changed fonts for both list text and title text
- changed font sizes to be bigger
- changed the column headers to be bolded
- made the column headers background green to match Ethical colors
- spaced the lines in the table to be less crowded and easier to read
- made the striped highlighting background lighter to make words easier to read
- changed the hover highlight color to yellow to match Ethical colors

2019-11-17 18:51 UTC, trev4ev requested changes
please take a look!

2019-11-17 18:51 UTC, trev4ev commented on src/components/DataTable.css
> +  color: rgb(80, 80, 80);
These can be combined (search how to apply style to multiple classes css)

2019-11-17 18:51 UTC, trev4ev commented on src/components/DataTable.js
> +          ]}
Pick up date does not exist for this table so you should be using another column

2019-11-17 18:51 UTC, trev4ev commented on src/components/Inventory.js
> +        <h1 className="header"> INVENTORY </h1>
Make this change to orders headers if you want all uppercase. Also please add a header to Announcements just so we are being consistent.

2019-11-17 18:51 UTC, trev4ev commented on src/components/DataTable.js
> +              filterable: false
can you add filtering (aka sorting) by item name. see orders table for how this is done

2019-11-17 19:15 UTC, abaruah117 submitted a review, later dismissed
Looks good, same as trevor's comments but once you resolve those should be good to go!

2019-11-19 07:45 UTC, katelyn-schmidt commented
Made changes to fix PR comments, please check it out! @trev4ev @abaruah117

2019-11-20 00:27 UTC, trev4ev approved these changes
lgtm

2019-11-20 18:41 UTC, abaruah117 approved these changes
lgtm

2019-11-20 23:49 UTC, merged