Restyled Login page, restyled for mobile.
codebase-berkeley/ethical-internal-website pull request #72
Opened 2019-12-09 03:58 UTC by ziyielenachen

1. Made Login Page prettier and works for mobile
2. Fixed the header of each page to fit mobile screen size
3. Fixed font size and row height in react table (DataTable.css) to fit mobile screen size (no more "..." for column names)
![Screen Shot 2019-12-08 at 6 34 21 PM](https://user-images.githubusercontent.com/55669681/70406265-07659080-19f5-11ea-9d62-337cc1982385.png)
![Screen Shot 2019-12-08 at 7 41 05 PM](https://user-images.githubusercontent.com/55669681/70406267-0896bd80-19f5-11ea-9316-292fad2a5738.png)
![Screen Shot 2019-12-08 at 7 41 37 PM](https://user-images.githubusercontent.com/55669681/70406270-0a608100-19f5-11ea-9195-e7cc21c6a268.png)
![Screen Shot 2019-12-08 at 4 55 12 PM](https://user-images.githubusercontent.com/55669681/70406272-0b91ae00-19f5-11ea-99fc-aa0e78ca4245.png)
![Screen Shot 2019-12-08 at 5 07 32 PM](https://user-images.githubusercontent.com/55669681/70406275-0d5b7180-19f5-11ea-9b02-88b5d5f47504.png)
![Screen Shot 2019-12-08 at 5 10 31 PM](https://user-images.githubusercontent.com/55669681/70406276-0e8c9e80-19f5-11ea-8686-c93cfc4af063.png)

2019-12-09 07:18 UTC, ziyielenachen commented
If you go to login page and the ethical logo is not turning or you get any error related to "styled", install this in your ethical-internal-website folder: npm install --save styled-components

2019-12-09 23:19 UTC, abaruah117 requested changes
Small changes, also put images in diff folder please! Instead of in components

2019-12-09 23:19 UTC, abaruah117 commented on src/components/Login.css
> +}
Add new line

2019-12-09 23:19 UTC, abaruah117 commented on src/components/Login.js
> +              {" "}
Remove these empty spaces

2019-12-10 08:39 UTC, ziyielenachen commented
All changes made.

2019-12-10 19:05 UTC, trev4ev submitted a review, later dismissed
lgtm

2019-12-10 19:28 UTC, abaruah117 submitted a review, later dismissed
lgtm

2019-12-10 19:29 UTC, abaruah117 commented
@ziyielenachen wait can you move the images folder outside of components? so it'd be src/images

2020-01-14 18:54 UTC, merged